### ISSUE TITLE
[Bug] Type Inference for Units

### ISSUE THREAD

**Issue by vonwenckstern** [MontiCore/OCL#1]
* `1 cm` will be parsed correctly as Type `Length`
* `7 mm^2` is parsed incorrectly as Type `Amount`, it should be Type `Area` http://jscience.org/api/javax/measure/quantity/Area.html

![image](https://user-images.githubusercontent.com/30497492/35768605-82d15f56-08fe-11e8-9a83-372cd73df12a.png)

**Comment by vonwenckstern** [comment]
```
classdiagram DefaultTypes {
   interface Collection {
      int size;
   }
   interface Set extends Collection;
   interface List extends Collection;
   
   interface Amount;
   class Length implements Amount;
   class Velocity implements Amount;
   class Area implements Amount;
   // ... add all other quantites from as class implementing Amount
   // http://jscience.org/api/javax/measure/quantity/Quantity.html

  // Addtionally in OCL normal numbers without units get the following type
  class Number implements Amount;
  class Integer extends Number;
  class Long extends Number;
  class Float extends Number;
  class Byte extends Number;
}
```
* In OCL ist die Zahl `3` kein Integer als `Type` sondern `Number`
   * `3` hat Type `Number`
   * `3.2` hat Type `Number`
   * `-3` hat Type `Number`
   * `-3.2` hat Type `Number`
* `3f` hat Type `Float`
* `3d` hat Type `Double`
* `3l` hat Type `Long`
* `0x...` hat Type `Byte`

**Comment by rumpe** [comment]
Ich würde das etwas anders sehen:
Typen sind Int, Long, Byte, Float, Double
und 3, -3 hat Int
0x33 also die Hexdarstellung ist eine Darstellungsform und kein Typ --> also Int
(0x33l könnte man noch als long durchgehen lassen)

Wie man Byte darstellt weiss ich nicht.

Ich würde hier die analogie zu Java gerne behalten.

**Comment by vonwenckstern** [comment]
@rumpe Sie haben Recht, ich habe es mal in Java REPL (http://www.javarepl.com/term.html) getestet, und es kam folgendes heraus:
* `3` und `-3` ist `Integer`
* `3.4` ist `Double`
* `0x33` ist auch `Integer`
* `3d` ist auch `Double`
* `3f` ist `Float`
* `3l` ist `Long`

@ferdinandmehlan dann übernehmen wir dies auch so für OCL damit wir mit Java gleich sind und Erweitern es mit den Einheiten Typen wie `Length`, `Velocity` wie oben beschrieben.

![image](https://user-images.githubusercontent.com/30497492/35770264-263d4006-0918-11e8-9525-cd8d2322af57.png)

**Comment by vonwenckstern** [comment]
@ferdinandmehlan dies ist doch jetzt gelöst?

**Comment by ferdinandmehlan** [comment]
Ja richtig, dieses Problem ist jetzt gelöst.

**Comment by vonwenckstern** [comment]
Hi @ferdinandmehlan, ,

wir haben leider noch einen Fehler:

![image](https://user-images.githubusercontent.com/30497492/38088961-1c3a3daa-335e-11e8-89cc-db9ab2efc014.png)

Vielleicht kannst du ja nochmal nachschauen, warum es nicht klappt.

Und das Save auf die Diskette funktioniert auch nicht mehr :( auf https://embeddedmontiarc.github.io/OCL/

**Comment by ferdinandmehlan** [comment]
@vonwenckstern ich habe dieses Problem und weiter mit zusammengesetzten Einheiten gelöst. Ich werde eine aktualisierte Version des Tools in OCLFiddle nachreichen.
