### ISSUE TITLE
Degree token recognition error

### ISSUE THREAD

**Issue by toezen** [MontiCore/OCL#12]
![screenshot 2018-04-04 10 10 49](https://user-images.githubusercontent.com/35234812/38296107-a20554c4-37f0-11e8-92be-343e0e11aa8c.png)

![screenshot 2018-04-04 10 11 00](https://user-images.githubusercontent.com/35234812/38296126-ad130c08-37f0-11e8-9325-c1019b284560.png)
@ferdinandmehlan please respond so we can talk about it

**Comment by ferdinandmehlan** [comment]
@toezen 
The test seems to pass locally and on travis.
This could be related to which unicode is used, as we had problems there, with how ° was parsed.
If only building the project is the problem, disabling the test should suffice.

**Comment by ferdinandmehlan** [comment]
No new information and could not be reproduced, therefor closed for now.
