### ISSUE TITLE
[Enhancement] Improve Error Message for Incompatibilities of InfixTypes

### ISSUE THREAD

**Issue by vonwenckstern** [MontiCore/OCL#2]
instead of the actual error message
* 0xCET01 left and right type of infix expression do not match

the following message would be more user-friendly
* 0xCET01 left and right type of infix expression `>` do not match: left type of `a.participants.size` is `Integer` whereas right type of `0 cm` is `Length` 

![image](https://user-images.githubusercontent.com/30497492/35768757-951eb8b8-0901-11e8-89e1-27d3af9e67f0.png)

**Comment by ferdinandmehlan** [comment]
The error messages are now more verbose.

**Comment by vonwenckstern** [comment]
@ferdinandmehlan I will test it when it is uploaded into the OCLFiddle, then I will close the issue
