### ISSUE TITLE
[Bug] Warning should be thrown as Log.warning and not as error

### ISSUE THREAD

**Issue by vonwenckstern** [MontiCore/OCL#3]
* warnings should be warnings (everything with `should be` in the message is a warning) and not an error
* check messages also when looking over CoCos
* OCL Tool (also Fiddle) should have no have `failQuick` set to `false` (so that we get all messages)
   * maybe we set later a check-box in OCLFiddle to control if we want failQuick or not (but by default it is better so that the first error such as file name does not hide all other)

https://github.com/MontiCore/OCL/blob/master/src/main/java/ocl/monticoreocl/ocl/_cocos/FileNameStartsWithLowerCaseLetter.java#L36

**Comment by ferdinandmehlan** [comment]
The CoCosare all cleaned up and the cli tool will not fail quick anymore. I'll close this issue when the features are pushed to the OCLFiddle page.

**Comment by vonwenckstern** [comment]
In the tool the output is now a warning, but the CLI says at the end that the model has errors; even if it has no errors and only a warning.

```
[WARN]  StringReader:<5,0>: 0xOCL03 invariant name 'b' should start with a capital letter.
There are errors!
```

I entered the following OCL constraint into the OCLFiddle:
```
package example.OCL;

import example.CDs.AuctionCD;

context Auction a inv b:
    a.participants.size > 0
```

**Comment by ferdinandmehlan** [comment]
@vonwenckstern I cannot confirm this behaviour. I get the warning, but the tool says success.
`[WARN]  StringReader:<5,0>: 0xOCL03 invariant name 'b' should start with a capital letter.
OCL Model loaded successfully!`
