### ISSUE TITLE
== should not bind higher than <=>

### ISSUE THREAD

**Issue by ferdinandmehlan** [MontiCore/OCL#6]

**Comment by ferdinandmehlan** [comment]
@vonwenckstern additionally should inExpressions bind higher than implies?
E.g. Shall we allow: `a in A implies somethingElse` or `(a in A) implies somethingElse`

**Comment by vonwenckstern** [comment]
Yes, in is higher than implies.

 

b in B implies a in A means actually (b in B) implies (a in A)

 

Von: ferdinandmehlan [mailto:notifications@github.com] 
Gesendet: Samstag, 3. März 2018 12:07
An: MontiCore/OCL <OCL@noreply.github.com>
Cc: Michael von Wenckstern <vonwenckstern@se-rwth.de>; Mention <mention@noreply.github.com>
Betreff: Re: [MontiCore/OCL] == should not bind higher than <=> (#6)

 

@vonwenckstern <https://github.com/vonwenckstern>  additionally should inExpressions bind higher than implies?
E.g. Shall we allow: a in A implies somethingElse or (a in A) implies somethingElse

**Comment by ferdinandmehlan** [comment]
The issue has been resolved.
